### ISSUE TITLE
Simple API

### ISSUE THREAD

**Issue by Ladvace** [TechnicPack/launcher-api#7]
I have a javascript project and I would like to know if there are some basic API URL where I can take all the mods and other assets

**Comment by Indemnity83** [comment]
The documentation for the API can be found here: https://docs.solder.io/docs/api

Is this what you're looking for?

**Comment by Ladvace** [comment]
yeah, thanks!

**Comment by Ladvace** [comment]
is there any way to get the entire mod list? And all version of a mod like doing: http://solder.technicpack.net/api/mod/Tekkit?

**Comment by Ladvace** [comment]
another stupid question, do you need to be logged to access mods?

**Comment by Indemnity83** [comment]
Depends on the version of Solder you're querying, support for the '/mod' endpoint was added to TechnicSolder in [PR 439](https://github.com/TechnicPack/TechnicSolder/pull/439). 

But the TechnicPack.net API (which is built in node) doesn't implement it.

**Comment by Ladvace** [comment]
I would like to access mods (and all relative assets)
