### ISSUE TITLE
Description of all required endpoints?

### ISSUE THREAD

**Issue by Mondanzo** [TechnicPack/launcher-api#8]
Is there some page or document to read what kind of responses are required and what endpoints are called from the Launcher and the website in order to rewrite the api without trying to understand php? 👀

**Comment by Indemnity83** [comment]
Check issue #7

**Comment by Mondanzo** [comment]
I've checked the issue already but it didn't had all the endpoints like the endpoint for linking Solder with the Technic Launcher account or, as you said, the description of what the endpoint /mod would return.

**Comment by Indemnity83** [comment]
There isn’t anymore documentation than what’s in those links, or reading though the PHP in this library.
